stages:
  - build
  - release

variables:
  GIT_STRATEGY: clone
  BRANCH_NAME: sparx-ci

before_script:
  - apk add --no-cache git jq bash zip
  - git config --global user.email "ci@broxus.com"
  - git config --global user.name "ci"
  - git checkout $CI_COMMIT_REF_NAME

build:
  stage: build
  image: node:23-alpine
  tags:
    - docker
  script:
    - bash scripts/create-tag.sh
    - npm ci
    - npm run build:prod
    - bash scripts/create-archive.sh -v prod
    - npm run build:beta
    - bash scripts/create-archive.sh -v beta
  artifacts:
    paths:
      - release/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_REF_NAME == $BRANCH_NAME'

release:
  stage: release
  image: node:23-alpine
  tags:
    - docker
  script:
    - bash scripts/create-tag.sh
    - bash scripts/update-package-version.sh
    - git add package.json
    - git commit -m "Update package version"
    - git push origin $CI_COMMIT_REF_NAME
    - npm ci
    - npm run build:prod
    - bash scripts/create-archive.sh -v prod
    - npm run build:beta
    - bash scripts/create-archive.sh -v beta
  artifacts:
    paths:
      - release/
    expire_in: 1 week
  when: manual
  rules:
    - if: '$CI_COMMIT_REF_NAME == $BRANCH_NAME'