stages:
  - build
  - notify
  - release

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 100
  BRANCH_NAME: sparx-dev

before_script:
  - apk add --no-cache git jq bash zip curl
  - git config --global user.email "ci@broxus.com"
  - git config --global user.name "${GITLAB_TOKEN_USERNAME}"

build:
  stage: build
  image: node:23-alpine
  tags:
    - docker
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - npm ci
    - npm run build:prod
    - bash scripts/create-archive.sh -v prod
    - npm run build:beta
    - bash scripts/create-archive.sh -v beta
  artifacts:
    paths:
      - release/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_REF_NAME == $BRANCH_NAME'

release:
  stage: release
  image: node:23-alpine
  tags:
    - docker
  script:
    - git clone https://${GITLAB_TOKEN_USERNAME}:${GITLAB_TOKEN_PASSWORD}@gitlab.broxus.com/wallet/browser-extension.git
    - cd browser-extension
    - git checkout $CI_COMMIT_REF_NAME
    - bash scripts/update-package-version.sh
    - bash scripts/create-tag.sh
  artifacts:
    paths:
      - release/
    expire_in: 1 week
  when: manual
  rules:
    - if: '$CI_COMMIT_REF_NAME == $BRANCH_NAME'

notify:
  stage: notify
  image: node:23-alpine
  tags:
    - docker
  script:
    - bash scripts/send-telegram-notification.sh
  artifacts:
    paths:
      - release/
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_REF_NAME == $BRANCH_NAME'
