stages:
  - build

build:
  stage: build
  image: node:23-alpine
  tags:
    - docker
  before_script:
    - apk add --no-cache git jq zip bash
  script:
    - npm ci
    - npm run release
  artifacts:
    paths:
      - release/
    expire_in: 1 week
  only:
    - dev